# Cypilot project configuration

version = "1.0"
project_root = ".."

[system]
name = "InsightSpec"
slug = "insight-spec"
kit = "cypilot-sdlc"

[kits]
[kits.cypilot-sdlc]
format = "Cypilot"
path = ".gen/kits/sdlc"

[kits.sdlc]
format = "Cypilot"
path = ".gen/kits/sdlc"
version = "5"
